- name: Remove swapfile from /etc/fstab
  become: true
  mount:
    path: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: true
  command: swapoff -a
  when: ansible_swaptotal_mb > 0