- name: Initialize the Kubernetes cluster using kubeadm
  become: true
  command: kubeadm init --pod-network-cidr {{ pod_network_cidr }} --apiserver-advertise-address {{ apiserver_advertise_address }}

- name: Setup kubeconfig
  become: true
  command: "{{ item }}"
  with_items:
    - mkdir -p {{ ansible_env.HOME }}/.kube
    - cp /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config
    - chown {{ ansible_env.USER }}:{{ ansible_env.USER }} {{ ansible_env.HOME }}/.kube/config

- name: Generate join command
  become: false
  command: kubeadm token create --print-join-command
  register: join_command

- name: Ensure files directory
  become: false
  local_action: file path="files/" state=directory

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="files/join-command"